### ISSUE TITLE
Enhance symbols fallback for windows

### ISSUE THREAD

**Issue by pantosha** [litixsoft/karma-mocha-reporter#100]
Currently karma-mocha-reporter uses overdue copy of [sindresorhus/log-symbols](/sindresorhus/log-symbols) . Compare [karma-mocha-reporter/symbols.js](litixsoft/karma-mocha-reporter/blob/master/symbols.js) with [log-symbols/index.js](/sindresorhus/log-symbols/blob/master/index.js).

It makes sense to update symbols.js or use [log-symbols](https://www.npmjs.com/package/log-symbols) npm package.

**Comment by 4kochi** [comment]
Good point. There was a reason why we add the symbols in code instead of using the log-symbols package directly. Will check this.

**Comment by 4kochi** [comment]
Published as v2.2.4
