### ISSUE TITLE
Broken on Windows 10

### ISSUE THREAD

**Issue by ZebraFlesh** [litixsoft/karma-mocha-reporter#101]
The switch to log-symbols breaks console output on Windows 10. I'm seeing [this exact issue](https://github.com/sindresorhus/log-symbols/issues/11) after upgrading to 2.2.4. (If I'm reading the unreleased resolution correctly, it's to not support Windows consoles with that package.)

Please revert b0aac74

**Comment by 4kochi** [comment]
I will wait for a new version of `log-symbols`. It is already fixed there.

**Comment by pantosha** [comment]
@4kochi, [log-symbols issue](/sindresorhus/log-symbols/issues/11) is already closed.

**Comment by 4kochi** [comment]
Published as v2.2.5
