### ISSUE TITLE
Console.log written to console twice

### ISSUE THREAD

**Issue by fraser-lowndes** [litixsoft/karma-mocha-reporter#102]
Reproduction repository here: https://github.com/fraser-lowndes/karma-double-console-log. Pull and use ng t --sr to see the isuse.

Any calls to `console.log` will be printed twice when using `karma-mocha-reporter` as the sole reporter in `karma.conf`. E.g. console.log('my log') is output to the console as 
```
LOG: 'my log'
LOG: 'my log'
```

**Comment by 4kochi** [comment]
I only see one message.

<img width="1147" alt="bildschirmfoto 2018-02-07 um 10 28 26" src="https://user-images.githubusercontent.com/1742426/35908696-bb04cd68-0bf1-11e8-8daa-2ac13b0e5e97.png">

**Comment by 4kochi** [comment]
Seems like someone else had the issue and fixed it in the @angular/cli

https://github.com/angular/angular-cli/issues/9528

**Comment by fraser-lowndes** [comment]
Excellent, I'll close this. Thanks for the help.
