### ISSUE TITLE
I only see describes, no its.

### ISSUE THREAD

**Issue by banderberg** [litixsoft/karma-mocha-reporter#110]
I am only seeing the text for describes in my Jasmine tests, but not the text for the its.  What do I need to do to see the its?

**Comment by candletrick** [comment]
> I am only seeing the text for describes in my Jasmine tests, but not the text for the its. What do I need to do to see the its?

In my case using karma.conf.js I had to add this to get the it() statement to show. It'd be nice if it was at the LOG_INFO rather than LOG_DEBUG level, but at least it shows:

```
module.exports = function(config) {
  config.set({
    logLevel: config.LOG_DEBUG,
  })
}
```

**Comment by banderberg** [comment]
I figured out my problem and the solution isn't even worth sharing.. basically just a dumb mistake.
