### ISSUE TITLE
Colored icons when config.colors is false

### ISSUE THREAD

**Issue by evanliomain** [litixsoft/karma-mocha-reporter#19]
The icons from log-symbols are colored when the color configuration is false.
![wrong_color](https://cloud.githubusercontent.com/assets/6391294/6097224/0a15d51a-afb5-11e4-9536-9abbcab1666d.png)

Just strip color when no color is required to remove this icons color:
```javascript
chalk.stripColor(logSymbols.error);
```

**Comment by 4kochi** [comment]
Ok, will have a look at it tomorrow. Thanks for reporting.
