### ISSUE TITLE
Not getting individual error reports if multiple browsers run tests and a test fails

### ISSUE THREAD

**Issue by sgerace** [litixsoft/karma-mocha-reporter#22]
I typically do most of my development/testing using a single browser and then run all of the browsers at the end using a different karma config file. When running with a single browser, I get full output for each failure (browser, stack trace, etc.). However, if I'm running multiple browsers and one fails, I only get a list of failed tests, not the stack trace for the failed browser (nor do I get any indication of which browser failed).

**Comment by 4kochi** [comment]
I run a short test in multiple browsers which fails. Looks all good. The browser in yellow are the ones where the test fails (in this case in all browsers).

![bildschirmfoto 2015-02-18 um 15 49 27](https://cloud.githubusercontent.com/assets/1742426/6249183/d7271cb2-b785-11e4-81c7-9c6049227cea.png)

One thing to note though is that the stack trace can be different in multiple runs. The stack trace comes directly from the browser, but each one have a different output. I did not found any solution to specify which stack trace from which browser should be used.

**Comment by Marsup** [comment]
I don't know if it's the same problem but I have the same symptom. I've traced it back to the item being wrong when printed :
```js
{
  "name": "My tests",
  "isRoot": true,
  "type": "describe",
  "skipped": false,
  "success": false,
  "items": {
    "should do something": {
      "name": "\u001b[32m✔\u001b[39m should do something",
      "isRoot": false,
      "type": "it",
      "skipped": false,
      "success": true,
      "count": 2,
      "failed": ["Firefox 31.0.0 (Linux)"],
      "log": ["AssertionError: expected { Object (length, prevObject, ...) } to have a length of 2 but got 0 (:0)\n"],
      "printed": true
    }
  },
  "printed": true
}

```

Notice the `describe` is failed, the `it` is not, but it has failures.
Using 1.0.0.

**Comment by 4kochi** [comment]
Ok, will try to reproduce this behavior. Could you please run the tests with the default reporter (progress) and look if the output of the error is the same. Thanks.

**Comment by Marsup** [comment]
With default reporter I get this :
```
Firefox 31.0.0 (Linux) My tests should do something FAILED
        AssertionError: expected { Object (length, prevObject, ...) } to have a length of 2 but got 0 (:0)
```

**Comment by 4kochi** [comment]
I looked through the code and see that most properties of the wrong printed item come directly from karma. Can you please tell me which version of karma you use.

**Comment by Marsup** [comment]
Using karma@0.12.31.

**Comment by Marsup** [comment]
Any progress on this ?

**Comment by 4kochi** [comment]
Not yet. Will check it again next week. Currently on vacations.

**Comment by 4kochi** [comment]
Have not found anything yet. Is the problem still there with the new karma version (0.13)?

**Comment by 4kochi** [comment]
Closing the issue due inactivity. Feel free to reopen if the issue still exists.
