### ISSUE TITLE
Multi-line error messages are rendered in a weird order

### ISSUE THREAD

**Issue by mik01aj** [litixsoft/karma-mocha-reporter#23]
Try this:

    expect('Hello\nWorld').toBe(0);

The displayed error message is:

```
FAILED TESTS:
  myTest
    myOtherTest
      ✖ should work
        PhantomJS 1.9.8 (Mac OS X)
      World' to be 0.
      Error: Expected 'Hello
          at /var/folders/(...)/blablabla-test.js:126:0
```

Related issues: https://github.com/jasmine/jasmine/issues/742 and https://github.com/jasmine/jasmine/issues/796

**Comment by 4kochi** [comment]
I will have a look. Thanks for reporting.

**Comment by 4kochi** [comment]
Ok, seems like a bug in karma-jasmine. My reporter gets the wrong input and just print it. I will try to find the bug in karma-jasmine.

**Comment by 4kochi** [comment]
karma-runner/karma-jasmine#79

**Comment by 4kochi** [comment]
The causing issue karma-runner/karma-jasmine#79 was fixed.
