### ISSUE TITLE
seems to ignore karma.conf logLevel setting

### ISSUE THREAD

**Issue by chrisbraddock** [litixsoft/karma-mocha-reporter#25]
With karma.conf logLevel set to config.LOG_WARN, LOG_DEBUG level messages are output to my console (e.g. console.log statements).

**Comment by 4kochi** [comment]
We are using the same functions to log the messages as the built in reporters in karma. So no `console.log()` statements anywhere. Which messages do you mean?

**Comment by chrisbraddock** [comment]
Sorry I meant console.log statements in my code - the code being tested. This is for an Angular app and we override Angular's $log methods with console.log methods because Angular $log swallows up the file names reported in Chrome DevTools console output. Anyway, it seems if we put the following in karma.conf the "issue" goes away:

```client: {
    captureConsole: false
}```

I guess **karma-spec-reporter**, which we were using previously, was doing this in code based on logLevel, so basically this was all a poor assumption by me.

Thanks!

**Comment by 4kochi** [comment]
No problem. And you are right, `karma-spec-reporter` is overriding the function `onBrowserLog()` and checks for the current log level of karma. We are using the original `onBrowserLog()` function of karma, which does not check the log level. If this really is an issue for you, maybe the karma repository is the right place to open an issue.
