### ISSUE TITLE
String diffs

### ISSUE THREAD

**Issue by monolithed** [litixsoft/karma-mocha-reporter#26]
Could you provide [string diffs](http://mochajs.org/#string-diffs)?

![1430089163985](https://cloud.githubusercontent.com/assets/803674/7339709/69527ab6-ec81-11e4-85ed-030068f9fa7a.png)

**Comment by 4kochi** [comment]
I will have a look at it.

**Comment by ttback** [comment]
Second this, trying to get the look like above screenshot and mentioned here: https://github.com/chaijs/chai/issues/106

**Comment by vitalets** [comment]
+1 for that feature

**Comment by sarod** [comment]
:+1:  would be great

**Comment by jreinert** [comment]
+1 for this

**Comment by 4kochi** [comment]
Released as v1.2.0
