### ISSUE TITLE
Ticks and Crosses don't show up when using bg colors

### ISSUE THREAD

**Issue by johnnyreilly** [litixsoft/karma-mocha-reporter#31]
The colors feature is fantastic!  However, there is a problem when using chalk's bg colors.  The icons (ticks / crosses etc that appear to the left of tests) don't show up.  Any idea why this might be?

Thanks again!

**Comment by 4kochi** [comment]
It's because the symbols are also styled by chalk and if for example the success color is bgGreen you will not see the symbol ✔ because it is also green but on a green background.

We can fix this by giving the symbol the same color from the config.

**Comment by 4kochi** [comment]
Released as v1.1.1

**Comment by johnnyreilly** [comment]
awesome!
