### ISSUE TITLE
Better handle duplicate descriptions

### ISSUE THREAD

**Issue by claycephas** [litixsoft/karma-mocha-reporter#36]
**Repro**

    describe('thing', function() {
        it('should do stuff', function() {
            expect(1+1).toEqual(2);
        });
        it('should do stuff', function() {
            expect(2+1).toEqual(3);
        });
    });

**Produces**

    thing
      √ should do stuff

    SUMMARY:
      √ 2 tests completed

**Expected**

    thing
      √ should do stuff
      √ should do stuff

    SUMMARY:
      √ 2 tests completed

**Comment by 4kochi** [comment]
Released as v1.1.4
