### ISSUE TITLE
Better full page reload failures

### ISSUE THREAD

**Issue by claycephas** [litixsoft/karma-mocha-reporter#37]
If some tests accidentally do a full page refresh, `karma-dots-reporter` reports the error, but `karma-mocha-reporter` doesn't make the failure as clear.

With dots reporter:

    ..............................................................................
    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      Some of your tests did a full page reload!
    PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 78 of 135 ERROR (0.2 secs / 0.2 secs)

With mocha reporter:

    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      Some of your tests did a full page reload!
    Finished in 0.222 secs / 0.217 secs
    SUMMARY:
    √ 78 tests completed

A better report would be:

    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      Some of your tests did a full page reload!
    Finished in 0.222 secs / 0.217 secs
    SUMMARY:
    √ 78 tests completed
    × 57 test failed

**Comment by 4kochi** [comment]
Can you please provide a test case which does the full page reload so that we can reproduce the behavior. That would help us a lot.

**Comment by claycephas** [comment]
I would think a test like this would reproduce it. However, I've so far not been able to reproduce with your demo tests.

    describe('thing', function() {
        it('should do stuff', function() {
            window.location.reload();
        });    
    });

**Comment by claycephas** [comment]
See this issue for more discussion of this karma error:

https://github.com/karma-runner/karma/issues/1101

**Comment by claycephas** [comment]
I was able to reproduce with this test:

    describe('thing', function() {
        it('should do stuff', function() {
            window.location.reload();
            expect(1+1).toEqual(2);
        });    
    });

output is this:

    START:
    29 12 2015 11:35:39.293:WARN [karma]: Port 9876 in use
    29 12 2015 11:35:39.297:INFO [karma]: Karma v0.13.16 server started at http://localhost:9877/
    29 12 2015 11:35:39.303:INFO [launcher]: Starting browser PhantomJS
    29 12 2015 11:35:39.824:INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket SPElEECVbW6K94
    R5AAAA with id 12782191
    thing
        √ should do stuff

    Finished in 0.004 secs / 0.002 secs

    SUMMARY:
    √ 1 test completed
    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
    Some of your tests did a full page reload!

    Finished in 0.021 secs / 0.002 secs

    SUMMARY:
    √ 1 test completed
    Warning: Task "karma:success" failed. Used --force, continuing.

    Done, but with warnings.

**Comment by 4kochi** [comment]
Thanks for the test case. I could easily reproduce the problem. But it is a bit tricky. Interestingly the onRunComplete method is called twice in this case, so the summary is printed twice. Also the test itself is successful for karma, so it is completed successful but the message with the full page reload is also printed.

I changed the handling in the onRunComplete method and hope the output is better now. Let me know if this acceptable for you.

```
START:
29 12 2015 21:19:55.379:INFO [karma]: Karma v0.13.16 server started at http://localhost:9876/
29 12 2015 21:19:55.385:INFO [launcher]: Starting browser PhantomJS
29 12 2015 21:19:57.008:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket JdUrzi4k9z9lGV5pAAAA with id 72983911
  thing
    ✔ should do stuff
    ✔ should do other stuff

Finished in 0.005 secs / 0.001 secs

SUMMARY:
✔ 2 tests completed
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Some of your tests did a full page reload!

✖ Error while running the tests! Exit code: 1

Warning: Task "karma:reload" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by claycephas** [comment]
Assuming the `x` and `Error while running the tests` are in red when colored I think that'd be great!

**Comment by 4kochi** [comment]
Yes, they are.

**Comment by 4kochi** [comment]
Published as v1.1.5

**Comment by maruthi1255** [comment]
Please update fix for the following issue.

PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Some of your tests did a full page reload

**Comment by 4kochi** [comment]
The error comes from karma. It has nothing to to with the reporter. Maybe you should update to the latest version of karma and PhantomJS.
