### ISSUE TITLE
Error after errors in tests are printed out

### ISSUE THREAD

**Issue by ShawnCholeva** [litixsoft/karma-mocha-reporter#39]
Hey, I am not really sure if this applies to karma-mocha-reporter, karma or gulp, but it only happens after the Failed Tests are printing (If all tests are passing I don't get the stacktrace printed out and it ends properly).  This is a screenshot of the error that I encountered.

![image](https://cloud.githubusercontent.com/assets/13332685/13155447/5dfcbbf2-d643-11e5-81b9-a22fef31fc1d.png)

**Comment by 4kochi** [comment]
To me it seems like a problem of gulp. I had something similar when the karma gulp task fails. Then gulp itself also fails and print an Exception. Can you please share your karma gulp task configuration. So I can compare it with my configuration.

**Comment by ShawnCholeva** [comment]
Sure thing, this is the gulp task.  Did you need to see the karma config as well?
```
gulp.task('test', function (done) {
    new Karma({
        configFile: __dirname + '/../../karma.conf.js',
        singleRun: true
    }, done).start();
});

```

**Comment by 4kochi** [comment]
Here is my task. I use the newest karma v0.13.21 So the server is first instanciated and then started. 

```
gulp.task('test', function(done) {
    var server = new karma.Server(localConfig, function (failCount) {
        done(failCount && new Error('Failed ' + failCount + ' tests.'));
    });
    server.start();
}
```

**Comment by 4kochi** [comment]
Hey @ShawnCholeva, do you still have the problem?

**Comment by afterbangx** [comment]
I was having this same problem just yesterday. I've read this is not the optimal solution but here is how I have fixed it for now: 

`gulp.task("unit-tests-all", function(done) {
	new Server({
		configFile: __dirname + "/karma.conf.js",
		singleRun: true
	}, function() { done(); }).start();
});`

**Comment by 4kochi** [comment]
Closing for now since this is a gulp problem. Thanks @afterbangx for your feedback.
