### ISSUE TITLE
[Request] Output test results into file

### ISSUE THREAD

**Issue by Kamilius** [litixsoft/karma-mocha-reporter#51]
It would be handy, for staging/production deploying needs to be able to save test output into, let's say an *.xml file. 
Is there a way to do it now? 
Currently didn't found an answer in API provided inside README.md

**Comment by 4kochi** [comment]
Currently there is nothing built in. If you are using Mac or Linux you can although pipe the results in a file. 

`karma start my.conf.js >> my.log.txt`

A better way would be to use a reporter which is optimized for structured output like the junit format (https://github.com/karma-runner/karma-junit-reporter)

But i am also open to any pull request for this case.

**Comment by 4kochi** [comment]
Closing but any ideas / pull request are appreciated.
