### ISSUE TITLE
Install issues when using Grunt 1.0.1

### ISSUE THREAD

**Issue by niemyjski** [litixsoft/karma-mocha-reporter#52]
```
- chalk@1.1.1 node_modules/karma-mocha-reporter/node_modules/chalk
exceptionless@2.5.0 /Users/blake/Code/Exceptionless.UI/src
+-- UNMET PEER DEPENDENCY grunt@1.0.1
`-- karma-mocha-reporter@2.0.1 
```

**Comment by 4kochi** [comment]
Can you please explain what you are exactly doing. Because I am not sure if `karma-mocha-reporter` is the problem. It has `grunt` as devDependency, but that should be ignored when install `karma-mocha-reporter` in your module.

**Comment by niemyjski** [comment]
I just tried to update https://github.com/exceptionless/Exceptionless.ui to the latest version and did npm install and got that error.

**Comment by niemyjski** [comment]
It was the only dependency I updated and from the error I believe it's caused by this library but I could be wrong.

**Comment by 4kochi** [comment]
I ran npm in your module and it works. The message `UNMET PEER DEPENDENCY grunt@1.0.1` comes from npm and refers to some grunt plugins you use which have a peer dependency on `grunt ~0.4.x`

At the end there is the following output:

```
npm WARN grunt-dom-munger@3.4.0 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was installed.
```

**Comment by niemyjski** [comment]
Thanks for the heads up and looking into it. Kinda weird they say that message when installing a new module. I'll look into it further.
