### ISSUE TITLE
Strange looking output on Travis 

### ISSUE THREAD

**Issue by marcoscaceres** [litixsoft/karma-mocha-reporter#54]
See:
https://travis-ci.org/w3c/respec/builds/124809750

It also seems to have regressed with regards to when multiple browsers are running. Running locally, I only see output for 1 browser, not two. 

You can test against:
http://github.com/w3c/respec/

If you would like... just npm install, and karma start.

**Comment by marcoscaceres** [comment]
To clarify, see specifically from this line: https://travis-ci.org/w3c/respec/builds/124809750#L1511

**Comment by 4kochi** [comment]
I have tested it locally and I can confirm that it looks weird. It seems like the reporter have a problem when the option `concurrency` is set in karma. I will check this.

**Comment by marcoscaceres** [comment]
Thanks for looking into it. If I can be of any help, just ping :)

**Comment by 4kochi** [comment]
Fixed in release v2.0.2

**Comment by marcoscaceres** [comment]
Woot 🎉. Trying it now

**Comment by marcoscaceres** [comment]
Ok, so the output is as expected, but it's still only outputting for the second browser, not the first (chromeCanary):
https://travis-ci.org/w3c/respec/builds/124951375#L1512

**Comment by 4kochi** [comment]
That is as expected. The report "collects" the information for a test run for each browser and when all browsers ran the test then the output is printed. In your case because of the concurrency of 1 only one browser runs at a time. And the last browsers triggers the output to be printed in the console.

**Comment by marcoscaceres** [comment]
Ah! Thanks for the clarification. Makes sense.
