### ISSUE TITLE
Special characters in tfs build output logs

### ISSUE THREAD

**Issue by afterbangx** [litixsoft/karma-mocha-reporter#60]
I have setup a gulp task to run our unit tests each time someone commits to master. We have a powershell script that is working for all of our gulp task except for the task that is running the tests. I have narrowed it down to some regex that is looking for the Starting and Finished strings in the gulp output. Specifically it is failing on the Finished string because of the special characters in the output. Here is an example of what the output in the tfs build logs looks like:

    2016-05-03T21:44:03.6342587Z [[90m16:44:03[39m] Finished '[36munit-tests-all[39m' after [35m17 s[39m

Changing the reporter back to the default 'progress' reporter produces output like this:

    2016-05-04T15:28:29.3935335Z [10:28:29] Finished 'unit-tests-all' after 16 s

Any idea what is causing the special characters in the output? Is it the colors? If so, is there any way to turn this off? We are dumping the results of the test runs into a slack channel for visibility and I didn't want to have to create a new custom script to strip these characters out if I can avoid it.

**Comment by 4kochi** [comment]
Seems to be a problem with the module `chalk`, which is used for the colored output. You can disable the colors by setting colors to `false` in the config.

```
// karma.conf.js
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],

    // reporters configuration
    reporters: ['mocha'],

    // reporter options
    mochaReporter: {
      colors: false
    },

    plugins: [
      'karma-jasmine',
      'karma-mocha-reporter'
    ]
  });
};
```

**Comment by 4kochi** [comment]
Closing this since it should be solved
