### ISSUE TITLE
The report does not show as displayed in Readme.md

### ISSUE THREAD

**Issue by e-cloud** [litixsoft/karma-mocha-reporter#64]
![image](https://cloud.githubusercontent.com/assets/5255354/16073546/f81bc7c8-3318-11e6-909d-fe2d26f43ad1.png)

As above, some of the karma start info went into **START section**(is it own by this plugin?).

and it doesn't output the full report.

I'm using the newest karma and mocha and newest version of this plugin.

**Comment by 4kochi** [comment]
I am using a defined hook from karma (`self.onRunStart()`). The behavior for when this is executed seems to have changed. Nothing I can do here.

Besides this, the full report should have been shown. Can you please share your karma.conf.js file so that I can try to reproduce the problem.

**Comment by e-cloud** [comment]
Here is my karma conf
```js
module.exports = function (config) {
	config.set({
		basePath: '',
		frameworks: ['mocha', 'chai', 'sinon'],
		files: [
			'bower_components/angular/angular.js',
			'bower_components/angular-mocks/angular-mocks.js',
			'src/*.js',
			'test/*.js'
		],
		exclude: [],
		preprocessors: {
			'src/*.js': ['coverage', 'babel']
		},
		babelPreprocessor: {
			options: {
				presets: ['es2015'],
				sourceMap: 'inline'
			},
			filename: function (file) {
				return file.originalPath.replace(/\.js$/, '.es5.js');
			},
			sourceFileName: function (file) {
				return file.originalPath;
			}
		},
		reporters: ['progress', 'mocha', 'coverage'],
		coverageReporter: {
			type: 'html',
			dir: 'coverage'
		},
		plugins: [
			'karma-babel-preprocessor',
			'karma-chrome-launcher',
			'karma-firefox-launcher',
			'karma-phantomjs-launcher',
			'karma-chai',
			'karma-sinon',
			'karma-mocha',
			'karma-mocha-reporter',
			'karma-coverage' // required for coverage
		],
		port: 9876,
		colors: true,
		logLevel: config.LOG_INFO,
		autoWatch: false,
		browsers: ['Chrome', 'Firefox', 'PhantomJS'],
		singleRun: true,
		concurrency: Infinity
	})
}
```

**Comment by stolidity** [comment]
@e-cloud This happens when you have both `progress` and `mocha` set as reporters in your config. Remove progress and you'll get the output you are expecting.

**Comment by e-cloud** [comment]
@stolidity, thanks very much, it seems the progress reporter override the mocha-reporter's action.

**Comment by 4kochi** [comment]
Thanks @stolidity for your help.
