### ISSUE TITLE
Seeing random console log when using karma v1.0.0 and above

### ISSUE THREAD

**Issue by slightlytyler** [litixsoft/karma-mocha-reporter#66]
When I start karma I see `decorator { '0': [Function], '1': 0, '2': true, '3': undefined }` when using the mocha reporter. If I remove the reporter I do not see the log. If I use v0.13.22 of karma I also do not see it.

**Comment by 4kochi** [comment]
This was a bug in `karma`  itself and is already fixed. https://github.com/karma-runner/karma/pull/2206

**Comment by slightlytyler** [comment]
@4kochi dang I looked at their issues first but guess I'm blind 😝

**Comment by 4kochi** [comment]
No Problem 😎✌️
