### ISSUE TITLE
console.log doesn't work in terminal (karma 1.1.0)

### ISSUE THREAD

**Issue by ovrmrw** [litixsoft/karma-mocha-reporter#67]
I'm using Karma v1.1.0, and now I have a trouble.
on v0.13.22 ... console.log to show log in terminal works.
on v1.1.0 ... doesn't work.

I think a config below is causing this trouble.
https://github.com/karma-runner/karma/blob/master/lib/config.js#L242-L246

The code below is handling "browserConsoleLogOptions".
https://github.com/karma-runner/karma/blob/master/lib/reporters/base.js#L5

sorry I don't know how to make a reporter plugin. but if this help you, I'm glad.

**Comment by 4kochi** [comment]
This is caused by a bug in karma. I opened a pull request where you can track the progress.

https://github.com/karma-runner/karma/pull/2220
