### ISSUE TITLE
Support tests with reserved prototype names

### ISSUE THREAD

**Issue by Krinkle** [litixsoft/karma-mocha-reporter#94]
```js
QUnit.test('constructor', function (assert) {;
// ..

QUnit.test('toString', function (assert) {;
// ...
```

Both of these cause the following warning, and the result is not included in the output:
> Reserved name for `it` block (constructor)! Please use an other name, otherwise the result are not printed correctly

See also #8 which reported this issue previously. It was closed since a warning was added and the crash mitigated by instead ignoring the result, but I don't see why we can't make it work. Arbitrary names shouldn't be made properties of a plain object.

It looks like this project intends to support Node v4 and higher, which means this could be stored using an ES5 null-inherited plain object (`Object.create(null)`) or by using a more appropiate store, such as ES6 `Set` or `Map`.

Where Set/Map solve the problem entirely, Object.create solves all cases except for the magic string `___proto__`.

Alternatively, you could also simply prefix the keys internally with a string of your choosing, e.g. `$` or `x`. That would naturally avoid all conflicts with prototype methods.

**Comment by 4kochi** [comment]
Released as v2.2.3
